window.productsData = [
  {
    id: 1,
    name: 'Mango',
    price: 200,
    plantype: 'fruit',
    image:
      'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRAc-1hq8hyZc2K_VP8qutknfXcBrbLk8hTjA&s',
    description:
      "A sweet and juicy tropical fruit known as the 'King of Fruits,' loved for its rich flavor and aroma. It is packed with vitamins and minerals that boost immunity and improve overall health.",
    advantages: [
      {
        key: 'Known as the king of fruits, highly nutritious.',
      },
      {
        key: 'Brings fragrance and greenery to the home environment.',
      },
      {
        key: 'Easily grows in warm climates.',
      },
    ],
    total_qty: 10,
    age_months: 5,
    height_cm: 10,
    pot_size_cm: 10,
    growth_rate: 'moderate',
    sunlight: 'full-sun',
    care_level: 'easy',
    return_policy_days: 3,
    replacement_policy: '',
    warranty: '',
    handling_time_days: 2,
    shipping_weight_g: 800,
  },
  {
    id: 2,
    name: 'Banana',
    price: 100,
    plantype: 'fruit',
    image:
      'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSZecTDdd9vXlxn2EXccRaapnCnqfwOXyKjKP1Og1_x996m1icD8PUOpJEx3Ei9ZCD5dNw&usqp=CAU',
    description:
      'A soft, nutritious fruit rich in potassium, perfect for maintaining heart health and bone strength. It also provides quick energy and helps reduce stress levels naturally.',
    advantages: [
      {
        key: 'Good for heart health.',
      },
      {
        key: 'Strengthens bones.',
      },
      {
        key: 'Reduces mental stress.',
      },
    ],
    total_qty: 10,
    age_months: 5,
    height_cm: 10,
    pot_size_cm: 10,
    growth_rate: 'moderate',
    sunlight: 'full-sun',
    care_level: 'easy',
    return_policy_days: 3,
    replacement_policy: '',
    warranty: '',
    handling_time_days: 2,
    shipping_weight_g: 800,
  },
  {
    id: 3,
    name: 'Pomegranate',
    price: 150,
    plantype: 'fruit',
    image:
      'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRGTQb1oJuhUIUdV1zmXwGbR5AISUJUFlRFXw&s',
    description:
      'A bright red fruit filled with juicy seeds that enhance blood health and increase hemoglobin. Its antioxidants also strengthen the heart and support overall well-being.',
    advantages: [
      {
        key: 'Excellent for increasing blood levels.',
      },
      {
        key: 'Helps boost hemoglobin.',
      },
      {
        key: 'Strengthens the heart.',
      },
    ],
    total_qty: 10,
    age_months: 5,
    height_cm: 10,
    pot_size_cm: 10,
    growth_rate: 'moderate',
    sunlight: 'full-sun',
    care_level: 'easy',
    return_policy_days: 3,
    replacement_policy: '',
    warranty: '',
    handling_time_days: 2,
    shipping_weight_g: 800,
  },
  {
    id: 4,
    name: 'Guava',
    price: 120,
    plantype: 'fruit',
    image:
      'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSvTpp9K4dyzU8VhtOXRlEgdF4nmLxlFAl-PA&s',
    description:
      'A tropical fruit high in Vitamin C that supports immunity and keeps you healthy year-round. Its sweet yet tangy flavor and fiber content make it excellent for digestion.',
    advantages: [
      {
        key: 'An excellent source of Vitamin C.',
      },
      {
        key: 'Helps boost immunity.',
      },
      {
        key: 'Improves digestion.',
      },
    ],
    total_qty: 10,
    age_months: 5,
    height_cm: 10,
    pot_size_cm: 10,
    growth_rate: 'moderate',
    sunlight: 'full-sun',
    care_level: 'easy',
    return_policy_days: 3,
    replacement_policy: '',
    warranty: '',
    handling_time_days: 2,
    shipping_weight_g: 800,
  },
  {
    id: 5,
    name: 'Lemon',
    price: 100,
    plantype: 'fruit',
    image:
      'https://images-eu.ssl-images-amazon.com/images/I/71WzNz3lPRL._AC_UL495_SR435,495_.jpg',
    description:
      'A tangy, refreshing citrus fruit rich in Vitamin C, essential for daily meals and good digestion. It helps cleanse the body, boost immunity, and maintain healthy skin.',
    advantages: [
      {
        key: 'Essential for daily meals.',
      },
      {
        key: 'Very good for the digestive system.',
      },
      {
        key: 'Rich in Vitamin C.',
      },
    ],
    total_qty: 10,
    age_months: 5,
    height_cm: 10,
    pot_size_cm: 10,
    growth_rate: 'moderate',
    sunlight: 'full-sun',
    care_level: 'easy',
    return_policy_days: 3,
    replacement_policy: '',
    warranty: '',
    handling_time_days: 2,
    shipping_weight_g: 800,
  },
  {
    id: 6,
    name: 'Amla',
    price: 150,
    plantype: 'fruit',
    image:
      'https://upload.wikimedia.org/wikipedia/commons/2/20/Otaheite_gooseberry.JPG',
    description:
      'A sour and tangy fruit known for its high Vitamin C and medicinal properties. It helps in digestion, boosts immunity, and promotes healthy hair and skin.',
    advantages: [
      {
        key: 'Provides relief from gas and acidity.',
      },
      {
        key: 'Boosts immunity.',
      },
      {
        key: 'Beneficial for hair and skin.',
      },
    ],
    total_qty: 10,
    age_months: 5,
    height_cm: 10,
    pot_size_cm: 10,
    growth_rate: 'moderate',
    sunlight: 'full-sun',
    care_level: 'easy',
    return_policy_days: 3,
    replacement_policy: '',
    warranty: '',
    handling_time_days: 2,
    shipping_weight_g: 800,
  },
  {
    id: 7,
    name: 'Chikoo',
    price: 120,
    plantype: 'fruit',
    image:
      'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQo55-X2W7JseTJAEUhVZkihHEYMMbVgdCcog&s',
    description:
      'A sweet and grainy tropical fruit loaded with energy and nutrients, loved by children. It also helps in respiratory problems like asthma, cold, and cough.',
    advantages: [
      {
        key: 'Sweet and nutritious fruit.',
      },
      {
        key: 'Helps with asthma, cold, and cough.',
      },
      {
        key: 'Excellent energy source for children.',
      },
    ],
    total_qty: 10,
    age_months: 5,
    height_cm: 10,
    pot_size_cm: 10,
    growth_rate: 'moderate',
    sunlight: 'full-sun',
    care_level: 'easy',
    return_policy_days: 3,
    replacement_policy: '',
    warranty: '',
    handling_time_days: 2,
    shipping_weight_g: 800,
  },
  {
    id: 8,
    name: 'Jamboo',
    price: 140,
    plantype: 'fruit',
    image:
      'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTDjv2jpj_L68dG9EL77jjwFeVnHilFluBD2Q&s',
    description:
      'A purple fruit with a unique tangy-sweet flavor, beneficial for people with diabetes. It also aids digestion and helps in controlling blood sugar levels.',
    advantages: [
      {
        key: 'Beneficial for diabetes.',
      },
      {
        key: 'Helps control blood sugar.',
      },
      {
        key: 'Improves digestion.',
      },
    ],
    total_qty: 10,
    age_months: 5,
    height_cm: 10,
    pot_size_cm: 10,
    growth_rate: 'moderate',
    sunlight: 'full-sun',
    care_level: 'easy',
    return_policy_days: 3,
    replacement_policy: '',
    warranty: '',
    handling_time_days: 2,
    shipping_weight_g: 800,
  },
  {
    id: 9,
    name: 'Ber',
    price: 110,
    plantype: 'fruit',
    image: 'https://m.media-amazon.com/images/I/61hK7cDtKCL._SX679_.jpg',
    description:
      'A small, tangy fruit rich in iron and vitamins, great for boosting hemoglobin levels. It is also helpful in treating cold and cough naturally.',
    advantages: [
      {
        key: 'Helps increase hemoglobin.',
      },
      {
        key: 'Beneficial for cold and cough.',
      },
      {
        key: 'Useful for a balanced diet.',
      },
    ],
    total_qty: 10,
    age_months: 5,
    height_cm: 10,
    pot_size_cm: 10,
    growth_rate: 'moderate',
    sunlight: 'full-sun',
    care_level: 'easy',
    return_policy_days: 3,
    replacement_policy: '',
    warranty: '',
    handling_time_days: 2,
    shipping_weight_g: 800,
  },
  {
    id: 10,
    name: 'Fig',
    price: 250,
    plantype: 'fruit',
    image:
      'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTJL_8YtAZE230YfAmBYaom2ipZilyut9_Klg&s',
    description:
      'A soft and sweet fruit rich in fiber and calcium, perfect for improving digestion. It also supports bone health and overall body strength.',
    advantages: [
      {
        key: 'Improves digestive system.',
      },
      {
        key: 'Provides calcium for bones.',
      },
      {
        key: 'Rich in fiber.',
      },
    ],
    total_qty: 10,
    age_months: 5,
    height_cm: 10,
    pot_size_cm: 10,
    growth_rate: 'moderate',
    sunlight: 'full-sun',
    care_level: 'easy',
    return_policy_days: 3,
    replacement_policy: '',
    warranty: '',
    handling_time_days: 2,
    shipping_weight_g: 800,
  },
  {
    id: 11,
    name: 'Jackfruit',
    price: 180,
    plantype: 'fruit',
    image:
      'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS-4aMq6FgazWxvJ5mwg-wiawW9ONBM93ZKzQ&s',
    description:
      'A large tropical fruit with a sweet aroma and unique taste, rich in nutrients and energy. Known for its high protein content and potential cancer-preventing properties.',
    advantages: [
      {
        key: 'Contains nutrients that prevent cancer.',
      },
      {
        key: 'Provides plant-based protein.',
      },
      {
        key: 'Has a distinct sweet fragrance.',
      },
    ],
    total_qty: 10,
    age_months: 5,
    height_cm: 10,
    pot_size_cm: 10,
    growth_rate: 'moderate',
    sunlight: 'full-sun',
    care_level: 'easy',
    return_policy_days: 3,
    replacement_policy: '',
    warranty: '',
    handling_time_days: 2,
    shipping_weight_g: 800,
  },
  {
    id: 12,
    name: 'Papaya',
    price: 130,
    plantype: 'fruit',
    image:
      'https://5.imimg.com/data5/SELLER/Default/2022/7/MV/IR/JM/106091433/fresh-papaya-1000x1000.jpg',
    description:
      'A soft orange tropical fruit rich in vitamins A and C, great for boosting immunity. It also supports eye health and improves digestion naturally.',
    advantages: [
      {
        key: 'Rich in vitamin A and C.',
      },
      {
        key: 'Beneficial for eyes.',
      },
      {
        key: 'Improves digestion.',
      },
    ],
    total_qty: 10,
    age_months: 5,
    height_cm: 10,
    pot_size_cm: 10,
    growth_rate: 'moderate',
    sunlight: 'full-sun',
    care_level: 'easy',
    return_policy_days: 3,
    replacement_policy: '',
    warranty: '',
    handling_time_days: 2,
    shipping_weight_g: 800,
  },
  {
    id: 13,
    name: 'Lychee',
    price: 200,
    plantype: 'fruit',
    image:
      'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQVT2psPBetw6PVglgGXUil_uFfP1dKbvaOzw&se',
    description:
      'A juicy and fragrant tropical fruit with a sweet floral taste, loved in summer. Packed with Vitamin C, it supports skin health and boosts immunity.',
    advantages: [
      {
        key: 'Improves skin health.',
      },
      {
        key: 'Boosts immunity.',
      },
      {
        key: 'Excellent source of vitamin C.',
      },
    ],
    total_qty: 10,
    age_months: 5,
    height_cm: 10,
    pot_size_cm: 10,
    growth_rate: 'moderate',
    sunlight: 'full-sun',
    care_level: 'easy',
    return_policy_days: 3,
    replacement_policy: '',
    warranty: '',
    handling_time_days: 2,
    shipping_weight_g: 800,
  },
  {
    id: 14,
    name: 'Mosambi',
    price: 120,
    plantype: 'fruit',
    image:
      'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRfqumd-r-Ppd_IO2k_Hw-ntCo7nXxQ4IyQgA&s',
    description:
      'A sweet and refreshing citrus fruit that is gentle on the stomach and hydrating. Helps improve digestion and provides a healthy dose of Vitamin C.',
    advantages: [
      {
        key: 'Helps with digestion.',
      },
      {
        key: 'Rich in Vitamin C.',
      },
      {
        key: 'Hydrating and refreshing.',
      },
    ],
    total_qty: 10,
    age_months: 5,
    height_cm: 10,
    pot_size_cm: 10,
    growth_rate: 'moderate',
    sunlight: 'full-sun',
    care_level: 'easy',
    return_policy_days: 3,
    replacement_policy: '',
    warranty: '',
    handling_time_days: 2,
    shipping_weight_g: 800,
  },
  {
    id: 15,
    name: 'Mulberry',
    price: 160,
    plantype: 'fruit',
    image:
      'https://magazine.outdoornebraska.gov/wp-content/uploads/2024/08/mulberries.png',
    description:
      'A sweet berry-like fruit rich in antioxidants and iron, perfect for boosting blood health. It also supports the immune system and overall wellness.',
    advantages: [
      {
        key: 'Improves blood circulation.',
      },
      {
        key: 'Rich in antioxidants.',
      },
      {
        key: 'Supports immunity.',
      },
    ],
    total_qty: 10,
    age_months: 5,
    height_cm: 10,
    pot_size_cm: 10,
    growth_rate: 'moderate',
    sunlight: 'full-sun',
    care_level: 'easy',
    return_policy_days: 3,
    replacement_policy: '',
    warranty: '',
    handling_time_days: 2,
    shipping_weight_g: 800,
  },
  {
    id: 16,
    name: 'Coconut',
    price: 80,
    plantype: 'fruit',
    image:
      'https://www.mtechgardens.com/cdn/shop/files/Coconut-Kalpasree-Hybrid_c9c663b4-e8b3-4edc-954d-674c2d9d62d3.png?crop=center&height=800&v=1717143280&width=800',
    description:
      'A tropical fruit with edible flesh and refreshing water, great for hydration. It also nourishes skin and provides healthy fats for energy.',
    advantages: [
      {
        key: 'Keeps the body hydrated.',
      },
      {
        key: 'Good for skin health.',
      },
      {
        key: 'Provides healthy fats.',
      },
    ],
    total_qty: 10,
    age_months: 5,
    height_cm: 10,
    pot_size_cm: 10,
    growth_rate: 'moderate',
    sunlight: 'full-sun',
    care_level: 'easy',
    return_policy_days: 3,
    replacement_policy: '',
    warranty: '',
    handling_time_days: 2,
    shipping_weight_g: 800,
  },
  {
    id: 17,
    name: 'Lemon (Khagdi)',
    price: 90,
    plantype: 'fruit',
    image:
      'https://5.imimg.com/data5/XE/YV/MY-16365438/kagzi-lemon-plant-1000x1000.jpg',
    description:
      'A hybrid lemon variety producing abundant tangy fruits, easy to grow in pots. Rich in Vitamin C, it enhances flavor in dishes and supports digestion.',
    advantages: [
      {
        key: 'Produces fruits year-round.',
      },
      {
        key: 'Grows easily in small spaces.',
      },
      {
        key: 'Rich in Vitamin C.',
      },
    ],
    total_qty: 10,
    age_months: 5,
    height_cm: 10,
    pot_size_cm: 10,
    growth_rate: 'moderate',
    sunlight: 'full-sun',
    care_level: 'easy',
    return_policy_days: 3,
    replacement_policy: '',
    warranty: '',
    handling_time_days: 2,
    shipping_weight_g: 800,
  },
  {
    id: 18,
    name: 'All Time Mango',
    price: 220,
    plantype: 'fruit',
    image:
      'https://m.media-amazon.com/images/I/6180HfYgZnL._UF1000,1000_QL80_.jpg',
    description:
      'A mango variety available in multiple seasons, known for its sweet taste and aroma. It supports digestion, boosts immunity, and improves eye health.',
    advantages: [
      {
        key: 'Available across multiple seasons.',
      },
      {
        key: 'Improves eye health.',
      },
      {
        key: 'Aids digestion.',
      },
    ],
    total_qty: 10,
    age_months: 5,
    height_cm: 10,
    pot_size_cm: 10,
    growth_rate: 'moderate',
    sunlight: 'full-sun',
    care_level: 'easy',
    return_policy_days: 3,
    replacement_policy: '',
    warranty: '',
    handling_time_days: 2,
    shipping_weight_g: 800,
  },
  {
    id: 19,
    name: 'Ramphal',
    price: 180,
    plantype: 'fruit',
    image:
      'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSigCcekg4Y211o8jjn-ILYImNpQlYn2S66NH8cbCnYnofwUJ0kCs8Xb4vhiobOCFeOaFU&usqp=CAU',
    description:
      'A soft and creamy tropical fruit with a mild sweetness, soothing for the stomach. It helps with acidity, improves digestion, and keeps the body cool.',
    advantages: [
      {
        key: 'Reduces acidity.',
      },
      {
        key: 'Improves digestion.',
      },
      {
        key: 'Keeps the body cool.',
      },
    ],
    total_qty: 10,
    age_months: 5,
    height_cm: 10,
    pot_size_cm: 10,
    growth_rate: 'moderate',
    sunlight: 'full-sun',
    care_level: 'easy',
    return_policy_days: 3,
    replacement_policy: '',
    warranty: '',
    handling_time_days: 2,
    shipping_weight_g: 800,
  },
  {
    id: 20,
    name: 'Gooseberry (Khata Amla)',
    price: 140,
    plantype: 'fruit',
    image:
      'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQJJZWc4gJV2AsSBqB4jlUoR096a22UT68ykQ&s',
    description:
      'A tangy fruit high in Vitamin C that helps fight seasonal illnesses. It strengthens immunity, supports digestion, and promotes healthy hair.',
    advantages: [
      {
        key: 'Prevents seasonal illnesses.',
      },
      {
        key: 'Strengthens immunity.',
      },
      {
        key: 'Promotes healthy hair.',
      },
    ],
    total_qty: 10,
    age_months: 5,
    height_cm: 10,
    pot_size_cm: 10,
    growth_rate: 'moderate',
    sunlight: 'full-sun',
    care_level: 'easy',
    return_policy_days: 3,
    replacement_policy: '',
    warranty: '',
    handling_time_days: 2,
    shipping_weight_g: 800,
  },

  {
    id: 21,
    name: 'Cherry',
    price: 250,
    plantype: 'fruit',
    image:
      'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRE-MFPAmhwNcuMghSqgi8WMKWw8VMS43rIGQ&s',
    description:
      'A small, sweet-tart fruit packed with antioxidants and vitamins. It helps improve sleep quality and reduces inflammation in the body.',
    advantages: [
      {
        key: 'Helps improve sleep quality.',
      },
      {
        key: 'Reduces inflammation.',
      },
      {
        key: 'Rich in antioxidants.',
      },
    ],
    total_qty: 10,
    age_months: 5,
    height_cm: 10,
    pot_size_cm: 10,
    growth_rate: 'moderate',
    sunlight: 'full-sun',
    care_level: 'easy',
    return_policy_days: 3,
    replacement_policy: '',
    warranty: '',
    handling_time_days: 2,
    shipping_weight_g: 800,
  },
  {
    id: 22,
    name: 'Star Fruit',
    price: 150,
    plantype: 'fruit',
    image:
      'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQmUwwbgg4qyCyaz-AJwv8Q1vCJ45MouYpLpA&s',
    description:
      'A unique star-shaped fruit with a crisp texture and tangy flavor. Rich in Vitamin C and antioxidants for better immunity.',
    advantages: [
      {
        key: 'Rich in Vitamin C.',
      },
      {
        key: 'Contains antioxidants.',
      },
      {
        key: 'Unique star shape.',
      },
    ],
    total_qty: 10,
    age_months: 5,
    height_cm: 10,
    pot_size_cm: 10,
    growth_rate: 'moderate',
    sunlight: 'full-sun',
    care_level: 'easy',
    return_policy_days: 3,
    replacement_policy: '',
    warranty: '',
    handling_time_days: 2,
    shipping_weight_g: 800,
  },
  {
    id: 23,
    name: 'Orange',
    price: 120,
    plantype: 'fruit',
    image:
      'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRfj8FzwWjGqhH_9cCWSIlK3acBrSsCF_sQZA&s',
    description:
      'A juicy citrus fruit loved worldwide for its sweet-tangy flavor. It supports skin health, strengthens immunity, and aids digestion.',
    advantages: [
      {
        key: 'Good for skin health.',
      },
      {
        key: 'Strengthens immunity.',
      },
      {
        key: 'Aids digestion.',
      },
    ],
    total_qty: 10,
    age_months: 5,
    height_cm: 10,
    pot_size_cm: 10,
    growth_rate: 'moderate',
    sunlight: 'full-sun',
    care_level: 'easy',
    return_policy_days: 3,
    replacement_policy: '',
    warranty: '',
    handling_time_days: 2,
    shipping_weight_g: 800,
  },
  {
    id: 24,
    name: 'Kesar Mango',
    price: 250,
    plantype: 'fruit',
    image:
      'https://shop.villkart.com/wp-content/uploads/2021/08/kesar-mango-3.png',
    description:
      'A premium mango variety famous for its saffron-colored pulp and rich sweetness. It is a seasonal delicacy and a source of vitamins and minerals.',
    advantages: [
      {
        key: 'Famous for saffron-colored pulp.',
      },
      {
        key: 'Very sweet in taste.',
      },
      {
        key: 'Seasonal delicacy.',
      },
    ],
    total_qty: 10,
    age_months: 5,
    height_cm: 10,
    pot_size_cm: 10,
    growth_rate: 'moderate',
    sunlight: 'full-sun',
    care_level: 'easy',
    return_policy_days: 3,
    replacement_policy: '',
    warranty: '',
    handling_time_days: 2,
    shipping_weight_g: 800,
  },
  {
    id: 25,
    name: 'Dragon Fruit',
    price: 300,
    plantype: 'fruit',
    image:
      'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSf4rL0rPhm4uEka9iwJj17teW-JFvnwWxKig&s',
    description:
      'An exotic tropical fruit with a bright pink skin and white or red flesh dotted with seeds. It is low in calories and high in fiber, vitamins, and antioxidants.',
    advantages: [
      {
        key: 'High in antioxidants.',
      },
      {
        key: 'Rich in fiber.',
      },
      {
        key: 'Boosts immunity.',
      },
    ],
    total_qty: 10,
    age_months: 5,
    height_cm: 10,
    pot_size_cm: 10,
    growth_rate: 'moderate',
    sunlight: 'full-sun',
    care_level: 'easy',
    return_policy_days: 3,
    replacement_policy: '',
    warranty: '',
    handling_time_days: 2,
    shipping_weight_g: 800,
  },
  {
    id: 27,
    name: 'Pineapple',
    price: 150,
    plantype: 'fruit',
    image:
      'https://upload.wikimedia.org/wikipedia/commons/c/cb/Pineapple_and_cross_section.jpg',
    description:
      'A tropical fruit with a sweet and tangy flavor, perfect for juices and desserts. It contains bromelain, which aids digestion and reduces inflammation.',
    advantages: [
      {
        key: 'Aids digestion.',
      },
      {
        key: 'Rich in Vitamin C.',
      },
      {
        key: 'Reduces inflammation.',
      },
    ],
    total_qty: 10,
    age_months: 5,
    height_cm: 10,
    pot_size_cm: 10,
    growth_rate: 'moderate',
    sunlight: 'full-sun',
    care_level: 'easy',
    return_policy_days: 3,
    replacement_policy: '',
    warranty: '',
    handling_time_days: 2,
    shipping_weight_g: 800,
  },
  {
    id: 28,
    name: 'Jamun',
    price: 180,
    plantype: 'fruit',
    image:
      'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR10o4Y5mBGd0IEdF71JiHHoK9CYq3L57Jsng&s',
    description:
      'A purple-black fruit with a unique sweet-tart flavor, known for controlling blood sugar. It is rich in antioxidants and supports oral health.',
    advantages: [
      {
        key: 'Helps control blood sugar.',
      },
      {
        key: 'Rich in antioxidants.',
      },
      {
        key: 'Supports oral health.',
      },
    ],
    total_qty: 10,
    age_months: 5,
    height_cm: 10,
    pot_size_cm: 10,
    growth_rate: 'moderate',
    sunlight: 'full-sun',
    care_level: 'easy',
    return_policy_days: 3,
    replacement_policy: '',
    warranty: '',
    handling_time_days: 2,
    shipping_weight_g: 800,
  },
  {
    id: 29,
    name: 'Sapota (Chikoo)',
    price: 160,
    plantype: 'fruit',
    image:
      'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSoDyu5Jmp9RqrRazpUHaPornF_jNtjOwKrRw&s',
    description:
      'A sweet brown tropical fruit rich in fiber and natural sugars. It boosts energy, aids digestion, and supports bone health.',
    advantages: [
      {
        key: 'Boosts energy levels.',
      },
      {
        key: 'Aids digestion.',
      },
      {
        key: 'Supports bone health.',
      },
    ],
    total_qty: 10,
    age_months: 5,
    height_cm: 10,
    pot_size_cm: 10,
    growth_rate: 'moderate',
    sunlight: 'full-sun',
    care_level: 'easy',
    return_policy_days: 3,
    replacement_policy: '',
    warranty: '',
    handling_time_days: 2,
    shipping_weight_g: 800,
  },
  {
    id: 30,
    name: 'Kinnow',
    price: 140,
    plantype: 'fruit',
    image:
      'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQZL2divtYlwYBoXlMr3Fys7_J4XbcyU4VrVA&s',
    description:
      'A juicy citrus fruit with a tangy-sweet taste, popular in winter. It is rich in Vitamin C, boosts immunity, and refreshes the body.',
    advantages: [
      {
        key: 'Boosts immunity.',
      },
      {
        key: 'Rich in Vitamin C.',
      },
      {
        key: 'Refreshes the body.',
      },
    ],
    total_qty: 10,
    age_months: 5,
    height_cm: 10,
    pot_size_cm: 10,
    growth_rate: 'moderate',
    sunlight: 'full-sun',
    care_level: 'easy',
    return_policy_days: 3,
    replacement_policy: '',
    warranty: '',
    handling_time_days: 2,
    shipping_weight_g: 800,
  },
  {
    id: 31,
    name: 'Black Grapes',
    price: 200,
    plantype: 'fruit',
    image:
      'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTZVHuDDKwXwU1ppN6kZ5P-WzzAboTskQQXLQ&s',
    description:
      'A juicy, sweet fruit rich in antioxidants and resveratrol for heart health. Also supports skin health and boosts energy naturally.',
    advantages: [
      {
        key: 'Supports heart health.',
      },
      {
        key: 'Rich in antioxidants.',
      },
      {
        key: 'Good for skin health.',
      },
    ],
    total_qty: 10,
    age_months: 5,
    height_cm: 10,
    pot_size_cm: 10,
    growth_rate: 'moderate',
    sunlight: 'full-sun',
    care_level: 'easy',
    return_policy_days: 3,
    replacement_policy: '',
    warranty: '',
    handling_time_days: 2,
    shipping_weight_g: 800,
  },
  {
    id: 32,
    name: 'Pear',
    price: 180,
    plantype: 'fruit',
    image:
      'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSm5vSOWoE9g8-Dfdocshlygn3TSY7JseT-JA&s',
    description:
      'A sweet, juicy fruit high in fiber and water content, keeping you hydrated. It supports digestion, heart health, and weight management.',
    advantages: [
      {
        key: 'High in fiber.',
      },
      {
        key: 'Supports heart health.',
      },
      {
        key: 'Aids weight management.',
      },
    ],
    total_qty: 10,
    age_months: 5,
    height_cm: 10,
    pot_size_cm: 10,
    growth_rate: 'moderate',
    sunlight: 'full-sun',
    care_level: 'easy',
    return_policy_days: 3,
    replacement_policy: '',
    warranty: '',
    handling_time_days: 2,
    shipping_weight_g: 800,
  },
  {
    id: 33,
    name: 'Custard Apple',
    price: 170,
    plantype: 'fruit',
    image:
      'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRqRtXIhWs5DCrVK2dPES3kElu193uQVoJaXQ&s',
    description:
      'A creamy, sweet tropical fruit packed with vitamins and minerals. It boosts energy, improves digestion, and supports immunity.',
    advantages: [
      {
        key: 'Boosts energy levels.',
      },
      {
        key: 'Improves digestion.',
      },
      {
        key: 'Strengthens immunity.',
      },
    ],
    total_qty: 10,
    age_months: 5,
    height_cm: 10,
    pot_size_cm: 10,
    growth_rate: 'moderate',
    sunlight: 'full-sun',
    care_level: 'easy',
    return_policy_days: 3,
    replacement_policy: '',
    warranty: '',
    handling_time_days: 2,
    shipping_weight_g: 800,
  },
  {
    id: 34,
    name: 'Jade Plant',
    price: 130,
    plantype: 'indoor',
    image:
      'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQQpiwvmFPDB3bqN9ThKdYFmdIgwHFBsgKIOQ&s',

    total_qty: 10,
    age_months: 5,
    height_cm: 10,
    pot_size_cm: 10,
    growth_rate: 'moderate',
    sunlight: 'full-sun',
    care_level: 'easy',
    return_policy_days: 3,
    replacement_policy: '',
    warranty: '',
    handling_time_days: 2,
    shipping_weight_g: 800,
    description: null,
    advantages: null,
  },
  {
    id: 35,
    name: 'Peach',
    price: 190,
    plantype: 'fruit',
    image:
      'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ2WU2uhUtf1Nt06oD98PhTcdH9WK9EyTOPKc5RRlDBTysIOD834zh-X6J4jzZ2VW7Cx0w&usqp=CAU',
    description:
      'A soft, juicy fruit with a pleasant aroma and delicate sweetness. It is rich in vitamins, supports skin health, and aids digestion.',
    advantages: [
      {
        key: 'Supports skin health.',
      },
      {
        key: 'Rich in vitamins.',
      },
      {
        key: 'Aids digestion.',
      },
    ],
    total_qty: 10,
    age_months: 5,
    height_cm: 10,
    pot_size_cm: 10,
    growth_rate: 'moderate',
    sunlight: 'full-sun',
    care_level: 'easy',
    return_policy_days: 3,
    replacement_policy: '',
    warranty: '',
    handling_time_days: 2,
    shipping_weight_g: 800,
  },
  {
    id: 36,
    name: 'Almond',
    price: 500,
    plantype: 'fruit',
    image:
      'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQoSBPgYW5mfbDCMSIPs_pTfSC3lQAhOwEg-g&s',
    description:
      'A nutritious nut rich in protein, healthy fats, and minerals, excellent for brain health. Also supports heart health and boosts energy levels.',
    advantages: [
      {
        key: 'Improves brain function.',
      },
      {
        key: 'Good for heart health.',
      },
      {
        key: 'Boosts energy levels.',
      },
    ],
    total_qty: 10,
    age_months: 5,
    height_cm: 10,
    pot_size_cm: 10,
    growth_rate: 'moderate',
    sunlight: 'full-sun',
    care_level: 'easy',
    return_policy_days: 3,
    replacement_policy: '',
    warranty: '',
    handling_time_days: 2,
    shipping_weight_g: 800,
  },
  {
    id: 37,
    name: 'Lady Palm',
    price: 300,
    plantype: 'indoor',
    image:
      'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRELK6FG0nhMFqdlsUtf62yU07gH_n9y-pqqA&s',
    description:
      'An elegant indoor palm that adds beauty and purifies indoor air. It also helps reduce stress and improve indoor humidity levels.',
    advantages: [
      {
        key: 'Purifies indoor air.',
      },
      {
        key: 'Reduces stress levels.',
      },
      {
        key: 'Improves indoor humidity.',
      },
    ],
    total_qty: 10,
    age_months: 5,
    height_cm: 10,
    pot_size_cm: 10,
    growth_rate: 'moderate',
    sunlight: 'full-sun',
    care_level: 'easy',
    return_policy_days: 3,
    replacement_policy: '',
    warranty: '',
    handling_time_days: 2,
    shipping_weight_g: 800,
  },
  {
    id: 38,
    name: 'Desi Rose',
    price: 150,
    plantype: 'outdoor',
    image:
      'https://5.imimg.com/data5/ECOM/Default/2024/2/389923283/AL/YF/YB/133331885/lightpinknadanroseliveplant-seed2plant-1-500x500.png',
    description:
      'A fragrant, traditional rose variety loved for its beauty and soothing scent. Used for decoration, perfumes, and natural remedies.',
    advantages: [
      {
        key: 'Beautiful fragrance.',
      },
      {
        key: 'Enhances garden beauty.',
      },
      {
        key: 'Can be used for natural remedies.',
      },
    ],
    total_qty: 10,
    age_months: 5,
    height_cm: 10,
    pot_size_cm: 10,
    growth_rate: 'moderate',
    sunlight: 'full-sun',
    care_level: 'easy',
    return_policy_days: 3,
    replacement_policy: '',
    warranty: '',
    handling_time_days: 2,
    shipping_weight_g: 800,
  },
  {
    id: 39,
    name: 'Neem',
    price: 80,
    plantype: 'herb',
    image:
      'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRYD5nlh33Cm4OZ2Mhacql5FWdpoSTq4U6aZQ&s',
    description:
      'A medicinal plant with powerful antibacterial and purifying properties. It keeps the environment fresh and supports skin health.',
    advantages: [
      {
        key: 'Has antibacterial properties.',
      },
      {
        key: 'Purifies the air.',
      },
      {
        key: 'Supports skin health.',
      },
    ],
    total_qty: 10,
    age_months: 5,
    height_cm: 10,
    pot_size_cm: 10,
    growth_rate: 'moderate',
    sunlight: 'full-sun',
    care_level: 'easy',
    return_policy_days: 3,
    replacement_policy: '',
    warranty: '',
    handling_time_days: 2,
    shipping_weight_g: 800,
  },
  {
    id: 40,
    name: 'Champa',
    price: 200,
    plantype: 'outdoor',
    image:
      'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT5FSvhqFC1N6uY4P4LtKFsysgy98kZ20cc4w&s',
    description:
      'A fragrant flowering plant popular in gardens and temples. Known for its beauty, spirituality, and calming presence.',
    advantages: [
      {
        key: 'Beautiful fragrance.',
      },
      {
        key: 'Popular for decoration.',
      },
      {
        key: 'Brings a calming presence.',
      },
    ],
    total_qty: 10,
    age_months: 5,
    height_cm: 10,
    pot_size_cm: 10,
    growth_rate: 'moderate',
    sunlight: 'full-sun',
    care_level: 'easy',
    return_policy_days: 3,
    replacement_policy: '',
    warranty: '',
    handling_time_days: 2,
    shipping_weight_g: 800,
  },
  {
    id: 41,
    name: 'Adenium',
    price: 250,
    plantype: 'outdoor',
    image:
      'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQNcPbZAmE5C82qW6thBfNz_tSWBtDMlyl5wA&s',
    description:
      'A colorful flowering succulent considered lucky in many cultures. It is easy to maintain and adds beauty to any space.',
    advantages: [
      {
        key: 'Considered a lucky plant.',
      },
      {
        key: 'Low maintenance.',
      },
      {
        key: 'Adds vibrant beauty.',
      },
    ],
    total_qty: 10,
    age_months: 5,
    height_cm: 10,
    pot_size_cm: 10,
    growth_rate: 'moderate',
    sunlight: 'full-sun',
    care_level: 'easy',
    return_policy_days: 3,
    replacement_policy: '',
    warranty: '',
    handling_time_days: 2,
    shipping_weight_g: 800,
  },
  {
    id: 42,
    name: 'Curry Leaf',
    price: 60,
    plantype: 'herb',
    image:
      'https://vgrgardens.com/wp-content/uploads/2025/02/curry-leaves-plant.png',
    description:
      'An aromatic herb essential in Indian cooking, adding a unique flavor and aroma to dishes. Also contains medicinal properties that support digestion and health.',
    advantages: [
      {
        key: 'Enhances flavor in cooking.',
      },
      {
        key: 'Has medicinal benefits.',
      },
      {
        key: 'Supports digestion.',
      },
    ],
    total_qty: 10,
    age_months: 5,
    height_cm: 10,
    pot_size_cm: 10,
    growth_rate: 'moderate',
    sunlight: 'full-sun',
    care_level: 'easy',
    return_policy_days: 3,
    replacement_policy: '',
    warranty: '',
    handling_time_days: 2,
    shipping_weight_g: 800,
  },
  {
    id: 44,
    name: 'Tulsi',
    price: 50,
    plantype: 'herb',
    image:
      'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTcstN8b7W_6LEf9saS8b82G1vBBVcu0rMZVw&s',
    description:
      'A sacred plant in Indian tradition known for its spiritual and medicinal value. It boosts immunity, purifies air, and relieves stress.',
    advantages: [
      {
        key: 'Boosts immunity.',
      },
      {
        key: 'Purifies indoor air.',
      },
      {
        key: 'Relieves stress.',
      },
    ],
    total_qty: 10,
    age_months: 5,
    height_cm: 10,
    pot_size_cm: 10,
    growth_rate: 'moderate',
    sunlight: 'full-sun',
    care_level: 'easy',
    return_policy_days: 3,
    replacement_policy: '',
    warranty: '',
    handling_time_days: 2,
    shipping_weight_g: 800,
  },
  {
    id: 45,
    name: 'Mint',
    price: 30,
    plantype: 'herb',
    image:
      'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR08qSb0WVqjRXA-wGcjknImrmeIxGuS3kDRA&s',
    description:
      'A refreshing herb used in drinks, chutneys, and dishes for its cooling flavor. It also aids digestion and freshens breath naturally.',
    advantages: [
      {
        key: 'Has cooling flavor.',
      },
      {
        key: 'Aids digestion.',
      },
      {
        key: 'Freshens breath.',
      },
    ],
    total_qty: 10,
    age_months: 5,
    height_cm: 10,
    pot_size_cm: 10,
    growth_rate: 'moderate',
    sunlight: 'full-sun',
    care_level: 'easy',
    return_policy_days: 3,
    replacement_policy: '',
    warranty: '',
    handling_time_days: 2,
    shipping_weight_g: 800,
  },
  {
    id: 46,
    name: 'Lady Palm',
    price: 360,
    plantype: 'indoor',
    image:
      'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRELK6FG0nhMFqdlsUtf62yU07gH_n9y-pqqA&s',

    total_qty: 10,
    age_months: 5,
    height_cm: 10,
    pot_size_cm: 10,
    growth_rate: 'moderate',
    sunlight: 'full-sun',
    care_level: 'easy',
    return_policy_days: 3,
    replacement_policy: '',
    warranty: '',
    handling_time_days: 2,
    shipping_weight_g: 800,
    description:
      'Lady Palm is a popular indoor plant with fan-shaped leaves, known for purifying air and adding elegance to interiors.',
    advantages: [
      { key: 'Air purifying' },
      { key: 'Low maintenance' },
      { key: 'Attractive foliage' },
    ],
  },
  {
    id: 47,
    name: 'Bilipatr',
    price: 100,
    plantype: 'outdoor',
    image:
      'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTIsyrt5G8oSKMB6ltdYBbNKPMV9Oy_K7vpTw&s',
    description:
      'A sacred plant in Indian tradition, especially in Lord Shiva worship. Also known for its medicinal benefits and air-purifying properties.',
    advantages: [
      {
        key: 'Used in religious worship.',
      },
      {
        key: 'Has medicinal properties.',
      },
      {
        key: 'Purifies the surrounding air.',
      },
    ],
    total_qty: 10,
    age_months: 5,
    height_cm: 10,
    pot_size_cm: 10,
    growth_rate: 'moderate',
    sunlight: 'full-sun',
    care_level: 'easy',
    return_policy_days: 3,
    replacement_policy: '',
    warranty: '',
    handling_time_days: 2,
    shipping_weight_g: 800,
  },
  {
    id: 48,
    name: 'Lemon Grass',
    price: 50,
    plantype: 'outdoor',
    image:
      'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ6K1Hw7Krd_dIZwH_9pJNytHyh3JF8VaKEOw&s',

    total_qty: 10,
    age_months: 5,
    height_cm: 10,
    pot_size_cm: 10,
    growth_rate: 'moderate',
    sunlight: 'full-sun',
    care_level: 'easy',
    return_policy_days: 3,
    replacement_policy: '',
    warranty: '',
    handling_time_days: 2,
    shipping_weight_g: 800,
    description:
      'Lemon Grass is an aromatic herb used in tea, soups, and traditional medicine. It has a refreshing citrus fragrance.',
    advantages: [
      { key: 'Used in herbal tea' },
      { key: 'Mosquito repellent' },
      { key: 'Medicinal value' },
    ],
  },
  {
    id: 49,
    name: 'Christmas Tree',
    price: 150,
    plantype: 'decorative',
    image:
      'https://png.pngtree.com/png-clipart/20230930/original/pngtree-christmas-tree-in-pot-png-image_13022856.png',

    total_qty: 10,
    age_months: 5,
    height_cm: 10,
    pot_size_cm: 10,
    growth_rate: 'moderate',
    sunlight: 'full-sun',
    care_level: 'easy',
    return_policy_days: 3,
    replacement_policy: '',
    warranty: '',
    handling_time_days: 2,
    shipping_weight_g: 800,
    description:
      'Christmas Tree is an evergreen conifer, symbol of celebration, widely used for decoration during Christmas.',
    advantages: [
      { key: 'Evergreen beauty' },
      { key: 'Ornamental use' },
      { key: 'Symbol of festivity' },
    ],
  },
  {
    id: 50,
    name: 'Neem (Limdo)',
    price: 80,
    plantype: 'outdoor',
    image:
      'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRYD5nlh33Cm4OZ2Mhacql5FWdpoSTq4U6aZQ&s',

    total_qty: 10,
    age_months: 5,
    height_cm: 10,
    pot_size_cm: 10,
    growth_rate: 'moderate',
    sunlight: 'full-sun',
    care_level: 'easy',
    return_policy_days: 3,
    replacement_policy: '',
    warranty: '',
    handling_time_days: 2,
    shipping_weight_g: 800,
    description:
      'Neem is a medicinal tree known as a natural purifier. Its leaves, bark, and seeds are used for health remedies.',
    advantages: [
      { key: 'Medicinal benefits' },
      { key: 'Natural pesticide' },
      { key: 'Air purifier' },
    ],
  },
  {
    id: 51,
    name: 'Ribbon Grass',
    price: 80,
    plantype: 'outdoor',
    image:
      'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTW9GaCDD7n1wDeB9k2i1K1vCF984WJ362aIdDPr3Wmkrrsg8bEATganCcL8OW1CbgWhos&usqp=CAU',

    total_qty: 10,
    age_months: 5,
    height_cm: 10,
    pot_size_cm: 10,
    growth_rate: 'moderate',
    sunlight: 'full-sun',
    care_level: 'easy',
    return_policy_days: 3,
    replacement_policy: '',
    warranty: '',
    handling_time_days: 2,
    shipping_weight_g: 800,
    description:
      'Ribbon Grass is a decorative plant with green and white striped leaves, ideal for borders and landscaping.',
    advantages: [
      { key: 'Attractive ornamental look' },
      { key: 'Easy to grow' },
      { key: 'Ground cover plant' },
    ],
  },
  {
    id: 52,
    name: 'Adenium',
    price: 150,
    plantype: 'decorative',
    image:
      'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQNcPbZAmE5C82qW6thBfNz_tSWBtDMlyl5wA&s',

    total_qty: 10,
    age_months: 5,
    height_cm: 10,
    pot_size_cm: 10,
    growth_rate: 'moderate',
    sunlight: 'full-sun',
    care_level: 'easy',
    return_policy_days: 3,
    replacement_policy: '',
    warranty: '',
    handling_time_days: 2,
    shipping_weight_g: 800,
    description:
      'Adenium, also known as Desert Rose, is a flowering plant with vibrant blooms and thick stems.',
    advantages: [
      { key: 'Beautiful flowers' },
      { key: 'Drought tolerant' },
      { key: 'Ideal for bonsai' },
    ],
  },
  {
    id: 53,
    name: 'Tej Patta',
    price: 50,
    plantype: 'outdoor',
    image:
      'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSgvGtllmHzFnnZiY0JtaTeEhFfNX1SmrijtQ&s',

    total_qty: 10,
    age_months: 5,
    height_cm: 10,
    pot_size_cm: 10,
    growth_rate: 'moderate',
    sunlight: 'full-sun',
    care_level: 'easy',
    return_policy_days: 3,
    replacement_policy: '',
    warranty: '',
    handling_time_days: 2,
    shipping_weight_g: 800,
    description:
      'Tej Patta (Bay Leaf) is a culinary spice and medicinal herb widely used in Indian cooking and Ayurveda.',
    advantages: [
      { key: 'Culinary use' },
      { key: 'Medicinal properties' },
      { key: 'Aromatic leaves' },
    ],
  },
  {
    id: 54,
    name: 'Areca Palm',
    price: 250,
    plantype: 'indoor',
    image:
      'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTBo5N1gxtDCbHD6X5_b8XvuPGAsUsEQmxuFQ&s',

    total_qty: 10,
    age_months: 5,
    height_cm: 10,
    pot_size_cm: 10,
    growth_rate: 'moderate',
    sunlight: 'full-sun',
    care_level: 'easy',
    return_policy_days: 3,
    replacement_policy: '',
    warranty: '',
    handling_time_days: 2,
    shipping_weight_g: 800,
    description:
      'Areca Palm is a popular indoor plant with feathery fronds, known for improving indoor air quality.',
    advantages: [
      { key: 'Air purifier' },
      { key: 'Attractive foliage' },
      { key: 'Good for indoors' },
    ],
  },
  {
    id: 55,
    name: 'Fern',
    price: 50,
    plantype: 'indoor',
    image:
      'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRLiubzo5rvuMcc1oAWbF_fH2tQzK4atvGvXg&s',

    total_qty: 10,
    age_months: 5,
    height_cm: 10,
    pot_size_cm: 10,
    growth_rate: 'moderate',
    sunlight: 'full-sun',
    care_level: 'easy',
    return_policy_days: 3,
    replacement_policy: '',
    warranty: '',
    handling_time_days: 2,
    shipping_weight_g: 800,
    description:
      'Fern is a lush green plant that grows in shaded areas, known for its delicate feathery leaves.',
    advantages: [
      { key: 'Air purifying' },
      { key: 'Adds greenery indoors' },
      { key: 'Low maintenance' },
    ],
  },
  {
    id: 56,
    name: 'Travellers Palm',
    price: 150,
    plantype: 'outdoor',
    image:
      'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQpkiOSu23JHi4X4CSF7hK7xyDIX8uYyv9W6A&s',

    total_qty: 10,
    age_months: 5,
    height_cm: 10,
    pot_size_cm: 10,
    growth_rate: 'moderate',
    sunlight: 'full-sun',
    care_level: 'easy',
    return_policy_days: 3,
    replacement_policy: '',
    warranty: '',
    handling_time_days: 2,
    shipping_weight_g: 800,
    description:
      'Travellers Palm is a tropical plant with fan-shaped leaves that collect rainwater, traditionally helpful to travellers.',
    advantages: [
      { key: 'Unique ornamental plant' },
      { key: 'Water storage in leaves' },
      { key: 'Tropical landscaping' },
    ],
  },
  {
    id: 57,
    name: 'Morpankhi',
    price: 100,
    plantype: 'outdoor',
    image:
      'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQbhYoVKRcZVZsaxWqWKprYzfL0yugWlkmTBA&s',

    total_qty: 10,
    age_months: 5,
    height_cm: 10,
    pot_size_cm: 10,
    growth_rate: 'moderate',
    sunlight: 'full-sun',
    care_level: 'easy',
    return_policy_days: 3,
    replacement_policy: '',
    warranty: '',
    handling_time_days: 2,
    shipping_weight_g: 800,
    description:
      'Morpankhi (Thuja) is a decorative evergreen shrub used in hedges and landscaping.',
    advantages: [
      { key: 'Ornamental use' },
      { key: 'Used as hedge plant' },
      { key: 'Easy to maintain' },
    ],
  },
  {
    id: 58,
    name: 'Tarmanlia',
    price: 150,
    plantype: 'outdoor',
    image:
      'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTPJLNG15Sh5bwHIbc14_sBlIYxxzmIs5FBww&s',

    total_qty: 10,
    age_months: 5,
    height_cm: 10,
    pot_size_cm: 10,
    growth_rate: 'moderate',
    sunlight: 'full-sun',
    care_level: 'easy',
    return_policy_days: 3,
    replacement_policy: '',
    warranty: '',
    handling_time_days: 2,
    shipping_weight_g: 800,
    description:
      'Tarmanlia (Tabernaemontana) is a flowering plant with fragrant white flowers, often used in gardens.',
    advantages: [
      { key: 'Fragrant flowers' },
      { key: 'Medicinal uses' },
      { key: 'Beautiful ornamental plant' },
    ],
  },
  {
    id: 59,
    name: 'Snake Plant',
    price: 150,
    plantype: 'indoor',
    image:
      'https://png.pngtree.com/png-clipart/20220707/ourmid/pngtree-realistic-snake-plant-in-hand-drawn-style-png-image_5744918.png',

    total_qty: 10,
    age_months: 5,
    height_cm: 10,
    pot_size_cm: 10,
    growth_rate: 'moderate',
    sunlight: 'full-sun',
    care_level: 'easy',
    return_policy_days: 3,
    replacement_policy: '',
    warranty: '',
    handling_time_days: 2,
    shipping_weight_g: 800,
    description:
      'Snake Plant, also called Mother-in-law’s Tongue, is a hardy plant known for its upright leaves and air-purifying qualities.',
    advantages: [
      { key: 'Air purifier' },
      { key: 'Low maintenance' },
      { key: 'Drought resistant' },
    ],
  },
  {
    id: 60,
    name: 'Dieffenbachia',
    price: 130,
    plantype: 'indoor',
    image:
      'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ1Zl0i5MtJymlGjeJZo19uWZQqdP0JCL6T5OiHWqkxeHUHwnsiLvAWcCIYG1qPvWaK-k4&usqp=CAU',

    total_qty: 10,
    age_months: 5,
    height_cm: 10,
    pot_size_cm: 10,
    growth_rate: 'moderate',
    sunlight: 'full-sun',
    care_level: 'easy',
    return_policy_days: 3,
    replacement_policy: '',
    warranty: '',
    handling_time_days: 2,
    shipping_weight_g: 800,
    description:
      'Dieffenbachia is a popular indoor plant with large patterned leaves, adding tropical beauty to interiors.',
    advantages: [
      { key: 'Attractive foliage' },
      { key: 'Air purifier' },
      { key: 'Good for indoors' },
    ],
  },
  {
    id: 61,
    name: 'Dracaena Mix',
    price: 140,
    plantype: 'indoor',
    image:
      'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR2XpaWH69B2HmWiheMWQSlBEe_cRLma3-gAyFzc6dv6b3CPHgBjSHr2NnMliugHQD2RZk&usqp=CAU',

    total_qty: 10,
    age_months: 5,
    height_cm: 10,
    pot_size_cm: 10,
    growth_rate: 'moderate',
    sunlight: 'full-sun',
    care_level: 'easy',
    return_policy_days: 3,
    replacement_policy: '',
    warranty: '',
    handling_time_days: 2,
    shipping_weight_g: 800,
    description:
      'Dracaena Mix includes varieties of Dracaena with colorful striped leaves, perfect as indoor decorative plants.',
    advantages: [
      { key: 'Air purifier' },
      { key: 'Attractive striped leaves' },
      { key: 'Indoor friendly' },
    ],
  },
  {
    id: 62,
    name: 'Syngonium Mix',
    price: 80,
    plantype: 'indoor',
    image:
      'https://rootsraja.in/cdn/shop/files/Syngonium_Gold_Allusion.png?v=1750321651',

    total_qty: 10,
    age_months: 5,
    height_cm: 10,
    pot_size_cm: 10,
    growth_rate: 'moderate',
    sunlight: 'full-sun',
    care_level: 'easy',
    return_policy_days: 3,
    replacement_policy: '',
    warranty: '',
    handling_time_days: 2,
    shipping_weight_g: 800,
    description:
      'Syngonium is a low-maintenance indoor plant with arrow-shaped leaves that come in different shades.',
    advantages: [
      { key: 'Air purifying' },
      { key: 'Variety of leaf colors' },
      { key: 'Compact indoor plant' },
    ],
  },
  {
    id: 63,
    name: 'Yellow Dracaena',
    price: 100,
    plantype: 'indoor',
    image:
      'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQvDa9SwCC8kVx8eFuvmzHsW2gVxLBcKF9MAXg2BTVKb5nNdqNSloVnCLCYQXXETgfUpj0&usqp=CAU',

    total_qty: 10,
    age_months: 5,
    height_cm: 10,
    pot_size_cm: 10,
    growth_rate: 'moderate',
    sunlight: 'full-sun',
    care_level: 'easy',
    return_policy_days: 3,
    replacement_policy: '',
    warranty: '',
    handling_time_days: 2,
    shipping_weight_g: 800,
    description:
      'Yellow Dracaena is an ornamental plant with yellow-striped leaves, widely used as an indoor and office plant.',
    advantages: [
      { key: 'Bright ornamental look' },
      { key: 'Air purifier' },
      { key: 'Low maintenance' },
    ],
  },
  {
    id: 64,
    name: 'Green Bamboo',
    price: 80,
    plantype: 'indoor',
    image: 'https://m.media-amazon.com/images/I/71jYS4temqL.jpg',

    total_qty: 10,
    age_months: 5,
    height_cm: 10,
    pot_size_cm: 10,
    growth_rate: 'moderate',
    sunlight: 'full-sun',
    care_level: 'easy',
    return_policy_days: 3,
    replacement_policy: '',
    warranty: '',
    handling_time_days: 2,
    shipping_weight_g: 800,
    description:
      'Green Bamboo is a fast-growing plant symbolizing luck, strength, and prosperity.',
    advantages: [
      { key: 'Symbol of good luck' },
      { key: 'Fast growing' },
      { key: 'Eco-friendly' },
    ],
  },
  {
    name: 'Mini Tagari',
    gujarati_name: 'મીની ટાગરી',
    id: 65,
    price: 80,
    plantype: 'outdoor',
    image: null,
    total_qty: 10,
    age_months: 5,
    height_cm: 10,
    pot_size_cm: 10,
    growth_rate: 'moderate',
    sunlight: 'full-sun',
    care_level: 'easy',
    return_policy_days: 3,
    replacement_policy: '',
    warranty: '',
    handling_time_days: 2,
    shipping_weight_g: 800,
    description:
      'Mini Tagari is a compact ornamental plant with small, colorful flowers. It is ideal for home gardens and pots, adding vibrant beauty to small spaces.',
    advantages: [
      {
        key: 'Compact plant, suitable for pots.',
      },
      {
        key: 'Bright flowers enhance beauty.',
      },
    ],
  },
  {
    name: 'Rat Rani',
    gujarati_name: 'રાતરાણી',
    id: 66,
    price: 80,
    plantype: 'outdoor',
    image: null,
    total_qty: 10,
    age_months: 5,
    height_cm: 10,
    pot_size_cm: 10,
    growth_rate: 'moderate',
    sunlight: 'full-sun',
    care_level: 'easy',
    return_policy_days: 3,
    replacement_policy: '',
    warranty: '',
    handling_time_days: 2,
    shipping_weight_g: 800,
    description:
      'Rat Rani, also known as Night-blooming Jasmine, is famous for its strong fragrance that spreads at night. It is widely planted for its aromatic and ornamental value.',
    advantages: [
      {
        key: 'Fragrant flowers bloom at night.',
      },
      {
        key: 'Good for home garden.',
      },
    ],
  },
  {
    name: 'Axora Lal',
    gujarati_name: 'ઇક્સોરા લાલ',
    id: 67,
    price: 80,
    plantype: 'outdoor',
    image: null,
    total_qty: 10,
    age_months: 5,
    height_cm: 10,
    pot_size_cm: 10,
    growth_rate: 'moderate',
    sunlight: 'full-sun',
    care_level: 'easy',
    return_policy_days: 3,
    replacement_policy: '',
    warranty: '',
    handling_time_days: 2,
    shipping_weight_g: 800,
    description:
      'Ixora Lal is a popular flowering shrub with bright red clusters of flowers. It is commonly used in decorative gardens for its long-lasting blooms.',
    advantages: [
      {
        key: 'Attractive red flowers.',
      },
      {
        key: 'Low maintenance plant.',
      },
    ],
  },
  {
    name: 'Axora Pila',
    gujarati_name: 'ઇક્સોરા પીળા',
    id: 68,
    price: 80,
    plantype: 'outdoor',
    image: null,
    total_qty: 10,
    age_months: 5,
    height_cm: 10,
    pot_size_cm: 10,
    growth_rate: 'moderate',
    sunlight: 'full-sun',
    care_level: 'easy',
    return_policy_days: 3,
    replacement_policy: '',
    warranty: '',
    handling_time_days: 2,
    shipping_weight_g: 800,
    description:
      'Ixora Pila is admired for its bright yellow flowers that bloom in clusters. It brings a cheerful look to gardens and is easy to grow.',
    advantages: [
      {
        key: 'Bright yellow blooms.',
      },
      {
        key: 'Good for decorative purpose.',
      },
    ],
  },
  {
    name: 'Axora White',
    gujarati_name: 'ઇક્સોરા સફેદ',
    id: 69,
    price: 80,
    plantype: 'outdoor',
    image: null,
    total_qty: 10,
    age_months: 5,
    height_cm: 10,
    pot_size_cm: 10,
    growth_rate: 'moderate',
    sunlight: 'full-sun',
    care_level: 'easy',
    return_policy_days: 3,
    replacement_policy: '',
    warranty: '',
    handling_time_days: 2,
    shipping_weight_g: 800,
    description:
      'Ixora White produces elegant white flowers that create a fresh and soothing effect in gardens. It is a hardy plant suitable for warm climates.',
    advantages: [
      {
        key: 'Elegant white flowers.',
      },
      {
        key: 'Adds freshness to garden.',
      },
    ],
  },
  {
    name: 'Karan Mixra (Red/White/Yellow)',
    gujarati_name: 'કરણ મિક્સ (લાલ/સફેદ/પીળા)',
    id: 70,
    price: 80,
    plantype: 'outdoor',
    image: null,
    total_qty: 10,
    age_months: 5,
    height_cm: 10,
    pot_size_cm: 10,
    growth_rate: 'moderate',
    sunlight: 'full-sun',
    care_level: 'easy',
    return_policy_days: 3,
    replacement_policy: '',
    warranty: '',
    handling_time_days: 2,
    shipping_weight_g: 800,
    description:
      'Karan Mixra is a versatile ornamental plant that comes in multiple colors including red, white, and yellow. It is perfect for creating vibrant landscaping.',
    advantages: [
      {
        key: 'Multiple color variety.',
      },
      {
        key: 'Best for ornamental gardening.',
      },
    ],
  },
  {
    name: 'Govadi Chovadi',
    gujarati_name: 'ગોવાડી ચોવાડી',
    id: 71,
    price: 80,
    plantype: 'outdoor',
    image: null,
    total_qty: 10,
    age_months: 5,
    height_cm: 10,
    pot_size_cm: 10,
    growth_rate: 'moderate',
    sunlight: 'full-sun',
    care_level: 'easy',
    return_policy_days: 3,
    replacement_policy: '',
    warranty: '',
    handling_time_days: 2,
    shipping_weight_g: 800,
    description:
      'Govadi Chovadi is a hardy shrub that thrives in outdoor conditions. It is often used in boundary plantations and landscaping due to its durability.',
    advantages: [
      {
        key: 'Hardy plant.',
      },
      {
        key: 'Suitable for outdoor landscaping.',
      },
    ],
  },
  {
    name: 'Thailen Tikoma',
    gujarati_name: 'થાઇલેન્ડ ટીકોમા',
    id: 72,
    price: 80,
    plantype: 'outdoor',
    image: null,
    total_qty: 10,
    age_months: 5,
    height_cm: 10,
    pot_size_cm: 10,
    growth_rate: 'moderate',
    sunlight: 'full-sun',
    care_level: 'easy',
    return_policy_days: 3,
    replacement_policy: '',
    warranty: '',
    handling_time_days: 2,
    shipping_weight_g: 800,
    description:
      'Thailand Tikoma is a fast-growing flowering tree that produces trumpet-shaped yellow flowers. It is known for attracting butterflies and adding beauty to roadsides.',
    advantages: [
      {
        key: 'Beautiful yellow flowers.',
      },
      {
        key: 'Attracts butterflies.',
      },
    ],
  },
  {
    name: 'Mogara',
    gujarati_name: 'મોગરો',
    id: 73,
    price: 80,
    plantype: 'outdoor',
    image: null,
    total_qty: 10,
    age_months: 5,
    height_cm: 10,
    pot_size_cm: 10,
    growth_rate: 'moderate',
    sunlight: 'full-sun',
    care_level: 'easy',
    return_policy_days: 3,
    replacement_policy: '',
    warranty: '',
    handling_time_days: 2,
    shipping_weight_g: 800,
    description:
      'Mogra, or Jasmine, is one of the most fragrant flowering plants. Its flowers are used in garlands, perfumes, and religious offerings.',
    advantages: [
      {
        key: 'Highly fragrant flowers.',
      },
      {
        key: 'Used in garlands and decoration.',
      },
    ],
  },
  {
    name: 'Jasud',
    gujarati_name: 'જાસુદ',
    id: 74,
    price: 80,
    plantype: 'outdoor',
    image: null,
    total_qty: 10,
    age_months: 5,
    height_cm: 10,
    pot_size_cm: 10,
    growth_rate: 'moderate',
    sunlight: 'full-sun',
    care_level: 'easy',
    return_policy_days: 3,
    replacement_policy: '',
    warranty: '',
    handling_time_days: 2,
    shipping_weight_g: 800,
    description:
      'Jasud (Hibiscus) is a tropical plant known for its large and vibrant flowers. It has medicinal value, especially in hair care and traditional remedies.',
    advantages: [
      {
        key: 'Medicinal uses for hair care.',
      },
      {
        key: 'Large colorful flowers.',
      },
    ],
  },
  {
    name: 'Jat ropa',
    gujarati_name: 'જાટ્રોપા',
    id: 75,
    price: 80,
    plantype: 'outdoor',
    image: null,
    total_qty: 10,
    age_months: 5,
    height_cm: 10,
    pot_size_cm: 10,
    growth_rate: 'moderate',
    sunlight: 'full-sun',
    care_level: 'easy',
    return_policy_days: 3,
    replacement_policy: '',
    warranty: '',
    handling_time_days: 2,
    shipping_weight_g: 800,
    description:
      'Jatropha is a hardy, drought-resistant plant that produces bright red flowers year-round. It is often used in fencing and as a biofuel plant.',
    advantages: [
      {
        key: 'Drought tolerant plant.',
      },
      {
        key: 'Bright red flowers all year.',
      },
    ],
  },
  {
    name: 'Gulab Kasmiri',
    gujarati_name: 'કાશ્મીરી ગુલાબ',
    id: 76,
    price: 80,
    plantype: 'outdoor',
    image: null,
    total_qty: 10,
    age_months: 5,
    height_cm: 10,
    pot_size_cm: 10,
    growth_rate: 'moderate',
    sunlight: 'full-sun',
    care_level: 'easy',
    return_policy_days: 3,
    replacement_policy: '',
    warranty: '',
    handling_time_days: 2,
    shipping_weight_g: 800,
    description:
      'Kashmiri Rose is a premium variety of rose known for its large size and strong fragrance. It is highly valued for decoration and perfumes.',
    advantages: [
      {
        key: 'Premium quality rose.',
      },
      {
        key: 'Strong fragrance and beauty.',
      },
    ],
  },
  {
    name: 'White Gulab',
    gujarati_name: 'સફેદ ગુલાબ',
    id: 77,
    price: 80,
    plantype: 'outdoor',
    image: null,
    total_qty: 10,
    age_months: 5,
    height_cm: 10,
    pot_size_cm: 10,
    growth_rate: 'moderate',
    sunlight: 'full-sun',
    care_level: 'easy',
    return_policy_days: 3,
    replacement_policy: '',
    warranty: '',
    handling_time_days: 2,
    shipping_weight_g: 800,
    description:
      'White Rose symbolizes peace and purity. It is widely used in decorations, religious offerings, and special occasions.',
    advantages: [
      {
        key: 'Pure white flowers.',
      },
      {
        key: 'Symbol of peace and purity.',
      },
    ],
  },
  {
    name: 'Aelamenda Pela',
    gujarati_name: 'એલામેંડા પીળા',
    id: 78,
    price: 80,
    plantype: 'outdoor',
    image: null,
    total_qty: 10,
    age_months: 5,
    height_cm: 10,
    pot_size_cm: 10,
    growth_rate: 'moderate',
    sunlight: 'full-sun',
    care_level: 'easy',
    return_policy_days: 3,
    replacement_policy: '',
    warranty: '',
    handling_time_days: 2,
    shipping_weight_g: 800,
    description:
      'Allamanda Pila is a tropical flowering shrub with bright yellow trumpet-shaped flowers. It grows well in warm climates and blooms year-round.',
    advantages: [
      {
        key: 'Evergreen shrub.',
      },
      {
        key: 'Bright yellow trumpet flowers.',
      },
    ],
  },
  {
    name: 'Draf Oro',
    gujarati_name: 'ડ્રાફ ઓરો',
    id: 79,
    price: 80,
    plantype: 'outdoor',
    image: null,
    total_qty: 10,
    age_months: 5,
    height_cm: 10,
    pot_size_cm: 10,
    growth_rate: 'moderate',
    sunlight: 'full-sun',
    care_level: 'easy',
    return_policy_days: 3,
    replacement_policy: '',
    warranty: '',
    handling_time_days: 2,
    shipping_weight_g: 800,
    description:
      'Draf Oro is an ornamental plant with unique foliage. It is commonly used for landscape gardening due to its decorative appeal.',
    advantages: [
      {
        key: 'Strong ornamental plant.',
      },
      {
        key: 'Ideal for landscaping.',
      },
    ],
  },
  {
    name: 'Dreshina',
    gujarati_name: 'ડ્રેસિના',
    id: 80,
    price: 80,
    plantype: 'outdoor',
    image: null,
    total_qty: 10,
    age_months: 5,
    height_cm: 10,
    pot_size_cm: 10,
    growth_rate: 'moderate',
    sunlight: 'full-sun',
    care_level: 'easy',
    return_policy_days: 3,
    replacement_policy: '',
    warranty: '',
    handling_time_days: 2,
    shipping_weight_g: 800,
    description:
      'Dracaena (Dreshina) is a popular indoor plant that requires very little care. It is also known for its ability to purify indoor air.',
    advantages: [
      {
        key: 'Popular indoor plant.',
      },
      {
        key: 'Improves air quality.',
      },
    ],
  },
  {
    name: 'Himalaya Draf',
    gujarati_name: 'હિમાલિયા ડ્રાફ',
    id: 81,
    price: 80,
    plantype: 'outdoor',
    image: null,
    total_qty: 10,
    age_months: 5,
    height_cm: 10,
    pot_size_cm: 10,
    growth_rate: 'moderate',
    sunlight: 'full-sun',
    care_level: 'easy',
    return_policy_days: 3,
    replacement_policy: '',
    warranty: '',
    handling_time_days: 2,
    shipping_weight_g: 800,
    description:
      'Himalaya Draf is a decorative indoor plant with attractive foliage. It is low maintenance and ideal for indoor decoration.',
    advantages: [
      {
        key: 'Attractive foliage.',
      },
      {
        key: 'Low maintenance indoor plant.',
      },
    ],
  },
  {
    name: 'Parijat',
    gujarati_name: 'પારિજાત',
    id: 82,
    price: 80,
    plantype: 'outdoor',
    image: null,
    total_qty: 10,
    age_months: 5,
    height_cm: 10,
    pot_size_cm: 10,
    growth_rate: 'moderate',
    sunlight: 'full-sun',
    care_level: 'easy',
    return_policy_days: 3,
    replacement_policy: '',
    warranty: '',
    handling_time_days: 2,
    shipping_weight_g: 800,
    description:
      'Parijat, also known as Night-flowering Jasmine, is considered sacred in many cultures. It blooms fragrant flowers at night and holds spiritual value.',
    advantages: [
      {
        key: 'Fragrant night-blooming flowers.',
      },
      {
        key: 'Cultural and spiritual value.',
      },
    ],
  },
  {
    name: 'Petra Croton',
    gujarati_name: 'પેટ્રા ક્રોટોન',
    id: 83,
    price: 80,
    plantype: 'outdoor',
    image: null,
    total_qty: 10,
    age_months: 5,
    height_cm: 10,
    pot_size_cm: 10,
    growth_rate: 'moderate',
    sunlight: 'full-sun',
    care_level: 'easy',
    return_policy_days: 3,
    replacement_policy: '',
    warranty: '',
    handling_time_days: 2,
    shipping_weight_g: 800,
    description:
      'Petra Croton is admired for its colorful foliage with shades of red, yellow, and green. It is widely used as an ornamental indoor plant.',
    advantages: [
      {
        key: 'Colorful foliage.',
      },
      {
        key: 'Perfect for indoor decoration.',
      },
    ],
  },
]
